function cost = jointParameterCost(inputs)
jointName = "r_elbow";
coordinateNumber = 0;
fn = @(value, model) adjustParentTranslation(model, jointName, ...
        coordinateNumber, value);
% cost = 5;
cost = computeInnerOptimization( ...
    [inputs.parameter], ...
    {fn}, ...
    inputs.auxdata.model, ...
    "simple_arm.trc", ...
    struct());
end

